// Copyright (C) 2005-2010 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema
// to C++ data binding compiler, in the Proprietary License mode.
// You should have received a proprietary license from Code Synthesis
// Tools CC prior to generating this code. See the license text for
// conditions.
//

// Begin prologue.
//

#define AOSLCPP_SOURCE 

//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "aoslcpp/aosl/change_transform.hpp"

#include <xsd/cxx/xml/dom/wildcard-source.hxx>

#include <xsd/cxx/xml/dom/parsing-source.hxx>

#include <xsd/cxx/tree/type-factory-map.hxx>

#include <xsd/cxx/tree/comparison-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::type_factory_plate< 0, char >
  type_factory_plate_init;

  static
  const ::xsd::cxx::tree::comparison_plate< 0, char >
  comparison_plate_init;
}

namespace aosl
{
  // Change_transform
  //

  Change_transform::
  Change_transform ()
  : ::aosl::Change_transform_base (),
    transformation_ (::xml_schema::Flags (), this)
  {
  }

  Change_transform::
  Change_transform (const ObjectType& object)
  : ::aosl::Change_transform_base (object),
    transformation_ (::xml_schema::Flags (), this)
  {
  }

  Change_transform::
  Change_transform (const Change_transform& x,
                    ::xml_schema::Flags f,
                    ::xml_schema::Container* c)
  : ::aosl::Change_transform_base (x, f, c),
    transformation_ (x.transformation_, f, this)
  {
  }

  Change_transform::
  Change_transform (const ::xercesc::DOMElement& e,
                    ::xml_schema::Flags f,
                    ::xml_schema::Container* c)
  : ::aosl::Change_transform_base (e, f | ::xml_schema::Flags::base, c),
    transformation_ (f, this)
  {
    if ((f & ::xml_schema::Flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e, true, true);
      this->parse (p, f);
    }
  }

  void Change_transform::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::Flags f)
  {
    this->::aosl::Change_transform_base::parse (p, f);

    for (; p.more_elements (); p.next_element ())
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // transformation
      //
      if (n.name () == "transformation" && n.namespace_ () == "http://artofsequence.org/aosl/1.x")
      {
        ::std::auto_ptr< TransformationType > r (
          TransformationTraits::create (i, f, this));

        this->transformation_.push_back (r);
        continue;
      }

      break;
    }
  }

  Change_transform* Change_transform::
  _clone (::xml_schema::Flags f,
          ::xml_schema::Container* c) const
  {
    return new class Change_transform (*this, f, c);
  }

  Change_transform::
  ~Change_transform ()
  {
  }

  static
  const ::xsd::cxx::tree::type_factory_initializer< 0, char, Change_transform >
  _xsd_Change_transform_type_factory_init (
    "change_transform",
    "http://artofsequence.org/aosl/1.x");

  static
  const ::xsd::cxx::tree::comparison_initializer< 0, char, Change_transform >
  _xsd_Change_transform_comparison_init;

  bool
  operator== (const Change_transform& x, const Change_transform& y)
  {
    if (!(static_cast< const ::aosl::Change_transform_base& > (x) ==
          static_cast< const ::aosl::Change_transform_base& > (y)))
      return false;

    if (!(x.transformation () == y.transformation ()))
      return false;

    return true;
  }

  bool
  operator!= (const Change_transform& x, const Change_transform& y)
  {
    return !(x == y);
  }
}

#include <ostream>

#include <xsd/cxx/tree/std-ostream-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::std_ostream_plate< 0, char >
  std_ostream_plate_init;
}

namespace aosl
{
  ::std::ostream&
  operator<< (::std::ostream& o, const Change_transform& i)
  {
    o << static_cast< const ::aosl::Change_transform_base& > (i);

    for (Change_transform::TransformationConstIterator
         b (i.transformation ().begin ()), e (i.transformation ().end ());
         b != e; ++b)
    {
      o << ::std::endl << "transformation: " << *b;
    }

    return o;
  }

  static
  const ::xsd::cxx::tree::std_ostream_initializer< 0, char, Change_transform >
  _xsd_Change_transform_std_ostream_init;
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace aosl
{
}

#include <ostream>
#include <xsd/cxx/tree/error-handler.hxx>
#include <xsd/cxx/xml/dom/serialization-source.hxx>

#include <xsd/cxx/tree/type-serializer-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::type_serializer_plate< 0, char >
  type_serializer_plate_init;
}

namespace aosl
{
  void
  operator<< (::xercesc::DOMElement& e, const Change_transform& i)
  {
    e << static_cast< const ::aosl::Change_transform_base& > (i);

    // transformation
    //
    for (Change_transform::TransformationConstIterator
         b (i.transformation ().begin ()), n (i.transformation ().end ());
         b != n; ++b)
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "transformation",
          "http://artofsequence.org/aosl/1.x",
          e));

      s << *b;
    }
  }

  static
  const ::xsd::cxx::tree::type_serializer_initializer< 0, char, Change_transform >
  _xsd_Change_transform_type_serializer_init (
    "change_transform",
    "http://artofsequence.org/aosl/1.x");
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

