// Copyright (C) 2005-2010 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema
// to C++ data binding compiler, in the Proprietary License mode.
// You should have received a proprietary license from Code Synthesis
// Tools CC prior to generating this code. See the license text for
// conditions.
//

// Begin prologue.
//

#define AOSLCPP_SOURCE 

//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "aoslcpp/aosl/object.hpp"

#include <xsd/cxx/xml/dom/wildcard-source.hxx>

#include <xsd/cxx/xml/dom/parsing-source.hxx>

#include <xsd/cxx/tree/type-factory-map.hxx>

#include <xsd/cxx/tree/comparison-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::type_factory_plate< 0, char >
  type_factory_plate_init;

  static
  const ::xsd::cxx::tree::comparison_plate< 0, char >
  comparison_plate_init;
}

namespace aosl
{
  // Object
  //

  Object::
  Object ()
  : ::xml_schema::Type (),
    properties_ (::xml_schema::Flags (), this),
    extension_ (::xml_schema::Flags (), this),
    children_ (::xml_schema::Flags (), this),
    id_ (::xml_schema::Flags (), this),
    active_ (active_default_value (), ::xml_schema::Flags (), this),
    resource_ (::xml_schema::Flags (), this),
    layer_ (::xml_schema::Flags (), this)
  {
  }

  Object::
  Object (const IdType& id)
  : ::xml_schema::Type (),
    properties_ (::xml_schema::Flags (), this),
    extension_ (::xml_schema::Flags (), this),
    children_ (::xml_schema::Flags (), this),
    id_ (id, ::xml_schema::Flags (), this),
    active_ (active_default_value (), ::xml_schema::Flags (), this),
    resource_ (::xml_schema::Flags (), this),
    layer_ (::xml_schema::Flags (), this)
  {
  }

  Object::
  Object (const Object& x,
          ::xml_schema::Flags f,
          ::xml_schema::Container* c)
  : ::xml_schema::Type (x, f, c),
    properties_ (x.properties_, f, this),
    extension_ (x.extension_, f, this),
    children_ (x.children_, f, this),
    id_ (x.id_, f, this),
    active_ (x.active_, f, this),
    resource_ (x.resource_, f, this),
    layer_ (x.layer_, f, this)
  {
  }

  Object::
  Object (const ::xercesc::DOMElement& e,
          ::xml_schema::Flags f,
          ::xml_schema::Container* c)
  : ::xml_schema::Type (e, f | ::xml_schema::Flags::base, c),
    properties_ (f, this),
    extension_ (f, this),
    children_ (f, this),
    id_ (f, this),
    active_ (f, this),
    resource_ (f, this),
    layer_ (f, this)
  {
    if ((f & ::xml_schema::Flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e, true, true);
      this->parse (p, f);
    }
  }

  void Object::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::Flags f)
  {
    for (; p.more_elements (); p.next_element ())
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // properties
      //
      if (n.name () == "properties" && n.namespace_ () == "http://artofsequence.org/aosl/1.x")
      {
        ::std::auto_ptr< PropertiesType > r (
          PropertiesTraits::create (i, f, this));

        if (!this->properties_)
        {
          this->properties_.set (r);
          continue;
        }
      }

      // extension
      //
      if (n.name () == "extension" && n.namespace_ () == "http://artofsequence.org/aosl/1.x")
      {
        ::std::auto_ptr< ExtensionType > r (
          ExtensionTraits::create (i, f, this));

        if (!this->extension_)
        {
          this->extension_.set (r);
          continue;
        }
      }

      // children
      //
      if (n.name () == "children" && n.namespace_ () == "http://artofsequence.org/aosl/1.x")
      {
        ::std::auto_ptr< ChildrenType > r (
          ChildrenTraits::create (i, f, this));

        if (!this->children_)
        {
          this->children_.set (r);
          continue;
        }
      }

      break;
    }

    while (p.more_attributes ())
    {
      const ::xercesc::DOMAttr& i (p.next_attribute ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      if (n.name () == "id" && n.namespace_ ().empty ())
      {
        ::std::auto_ptr< IdType > r (
          IdTraits::create (i, f, this));

        this->id_.set (r);
        continue;
      }

      if (n.name () == "active" && n.namespace_ ().empty ())
      {
        this->active_.set (ActiveTraits::create (i, f, this));
        continue;
      }

      if (n.name () == "resource" && n.namespace_ ().empty ())
      {
        ::std::auto_ptr< ResourceType > r (
          ResourceTraits::create (i, f, this));

        this->resource_.set (r);
        continue;
      }

      if (n.name () == "layer" && n.namespace_ ().empty ())
      {
        ::std::auto_ptr< LayerType > r (
          LayerTraits::create (i, f, this));

        this->layer_.set (r);
        continue;
      }
    }

    if (!id_.present ())
    {
      throw ::xsd::cxx::tree::expected_attribute< char > (
        "id",
        "");
    }

    if (!active_.present ())
    {
      this->active_.set (active_default_value ());
    }
  }

  Object* Object::
  _clone (::xml_schema::Flags f,
          ::xml_schema::Container* c) const
  {
    return new class Object (*this, f, c);
  }

  Object::
  ~Object ()
  {
  }

  static
  const ::xsd::cxx::tree::type_factory_initializer< 0, char, Object >
  _xsd_Object_type_factory_init (
    "object",
    "http://artofsequence.org/aosl/1.x");

  static
  const ::xsd::cxx::tree::comparison_initializer< 0, char, Object >
  _xsd_Object_comparison_init;

  bool
  operator== (const Object& x, const Object& y)
  {
    if (!(x.properties () == y.properties ()))
      return false;

    if (!(x.extension () == y.extension ()))
      return false;

    if (!(x.children () == y.children ()))
      return false;

    if (!(x.id () == y.id ()))
      return false;

    if (!(x.active () == y.active ()))
      return false;

    if (!(x.resource () == y.resource ()))
      return false;

    if (!(x.layer () == y.layer ()))
      return false;

    return true;
  }

  bool
  operator!= (const Object& x, const Object& y)
  {
    return !(x == y);
  }
}

#include <ostream>

#include <xsd/cxx/tree/std-ostream-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::std_ostream_plate< 0, char >
  std_ostream_plate_init;
}

namespace aosl
{
  ::std::ostream&
  operator<< (::std::ostream& o, const Object& i)
  {
    if (i.properties ())
    {
      o << ::std::endl << "properties: " << *i.properties ();
    }

    if (i.extension ())
    {
      o << ::std::endl << "extension: " << *i.extension ();
    }

    if (i.children ())
    {
      o << ::std::endl << "children: " << *i.children ();
    }

    o << ::std::endl << "id: " << i.id ();
    o << ::std::endl << "active: " << i.active ();
    if (i.resource ())
    {
      o << ::std::endl << "resource: " << *i.resource ();
    }

    if (i.layer ())
    {
      o << ::std::endl << "layer: " << *i.layer ();
    }

    return o;
  }

  static
  const ::xsd::cxx::tree::std_ostream_initializer< 0, char, Object >
  _xsd_Object_std_ostream_init;
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace aosl
{
}

#include <ostream>
#include <xsd/cxx/tree/error-handler.hxx>
#include <xsd/cxx/xml/dom/serialization-source.hxx>

#include <xsd/cxx/tree/type-serializer-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::type_serializer_plate< 0, char >
  type_serializer_plate_init;
}

namespace aosl
{
  void
  operator<< (::xercesc::DOMElement& e, const Object& i)
  {
    e << static_cast< const ::xml_schema::Type& > (i);

    // properties
    //
    if (i.properties ())
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "properties",
          "http://artofsequence.org/aosl/1.x",
          e));

      s << *i.properties ();
    }

    // extension
    //
    if (i.extension ())
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "extension",
          "http://artofsequence.org/aosl/1.x",
          e));

      s << *i.extension ();
    }

    // children
    //
    if (i.children ())
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "children",
          "http://artofsequence.org/aosl/1.x",
          e));

      s << *i.children ();
    }

    // id
    //
    {
      ::xercesc::DOMAttr& a (
        ::xsd::cxx::xml::dom::create_attribute (
          "id",
          e));

      a << i.id ();
    }

    // active
    //
    {
      ::xercesc::DOMAttr& a (
        ::xsd::cxx::xml::dom::create_attribute (
          "active",
          e));

      a << i.active ();
    }

    // resource
    //
    if (i.resource ())
    {
      ::xercesc::DOMAttr& a (
        ::xsd::cxx::xml::dom::create_attribute (
          "resource",
          e));

      a << *i.resource ();
    }

    // layer
    //
    if (i.layer ())
    {
      ::xercesc::DOMAttr& a (
        ::xsd::cxx::xml::dom::create_attribute (
          "layer",
          e));

      a << *i.layer ();
    }
  }

  static
  const ::xsd::cxx::tree::type_serializer_initializer< 0, char, Object >
  _xsd_Object_type_serializer_init (
    "object",
    "http://artofsequence.org/aosl/1.x");
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

