// Copyright (C) 2005-2010 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema
// to C++ data binding compiler, in the Proprietary License mode.
// You should have received a proprietary license from Code Synthesis
// Tools CC prior to generating this code. See the license text for
// conditions.
//

// Begin prologue.
//

#define AOSLCPP_SOURCE 

//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "aoslcpp/aosl/spatial_area.hpp"

#include <xsd/cxx/xml/dom/wildcard-source.hxx>

#include <xsd/cxx/xml/dom/parsing-source.hxx>

#include <xsd/cxx/tree/type-factory-map.hxx>

#include <xsd/cxx/tree/comparison-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::type_factory_plate< 0, char >
  type_factory_plate_init;

  static
  const ::xsd::cxx::tree::comparison_plate< 0, char >
  comparison_plate_init;
}

namespace aosl
{
  // Spatial_area
  //

  Spatial_area::
  Spatial_area ()
  : ::aosl::Vector (),
    system_ (::xml_schema::Flags (), this)
  {
  }

  Spatial_area::
  Spatial_area (const Spatial_area& x,
                ::xml_schema::Flags f,
                ::xml_schema::Container* c)
  : ::aosl::Vector (x, f, c),
    system_ (x.system_, f, this)
  {
  }

  Spatial_area::
  Spatial_area (const ::xercesc::DOMElement& e,
                ::xml_schema::Flags f,
                ::xml_schema::Container* c)
  : ::aosl::Vector (e, f | ::xml_schema::Flags::base, c),
    system_ (f, this)
  {
    if ((f & ::xml_schema::Flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e, true, true);
      this->parse (p, f);
    }
  }

  void Spatial_area::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::Flags f)
  {
    this->::aosl::Vector::parse (p, f);

    for (; p.more_elements (); p.next_element ())
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // system
      //
      if (n.name () == "system" && n.namespace_ () == "http://artofsequence.org/aosl/1.x")
      {
        ::std::auto_ptr< SystemType > r (
          SystemTraits::create (i, f, this));

        if (!this->system_)
        {
          this->system_.set (r);
          continue;
        }
      }

      break;
    }
  }

  Spatial_area* Spatial_area::
  _clone (::xml_schema::Flags f,
          ::xml_schema::Container* c) const
  {
    return new class Spatial_area (*this, f, c);
  }

  Spatial_area::
  ~Spatial_area ()
  {
  }

  bool
  operator== (const Spatial_area& x, const Spatial_area& y)
  {
    if (!(static_cast< const ::aosl::Vector& > (x) ==
          static_cast< const ::aosl::Vector& > (y)))
      return false;

    if (!(x.system () == y.system ()))
      return false;

    return true;
  }

  bool
  operator!= (const Spatial_area& x, const Spatial_area& y)
  {
    return !(x == y);
  }
}

#include <ostream>

#include <xsd/cxx/tree/std-ostream-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::std_ostream_plate< 0, char >
  std_ostream_plate_init;
}

namespace aosl
{
  ::std::ostream&
  operator<< (::std::ostream& o, const Spatial_area& i)
  {
    o << static_cast< const ::aosl::Vector& > (i);

    if (i.system ())
    {
      o << ::std::endl << "system: " << *i.system ();
    }

    return o;
  }
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace aosl
{
}

#include <ostream>
#include <xsd/cxx/tree/error-handler.hxx>
#include <xsd/cxx/xml/dom/serialization-source.hxx>

#include <xsd/cxx/tree/type-serializer-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::type_serializer_plate< 0, char >
  type_serializer_plate_init;
}

namespace aosl
{
  void
  operator<< (::xercesc::DOMElement& e, const Spatial_area& i)
  {
    e << static_cast< const ::aosl::Vector& > (i);

    // system
    //
    if (i.system ())
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "system",
          "http://artofsequence.org/aosl/1.x",
          e));

      s << *i.system ();
    }
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

