#ifndef HGUARD_UTILCPP_HARDCONFIG_HPP__
#define HGUARD_UTILCPP_HARDCONFIG_HPP__
#pragma once


#ifdef _DEBUG 
	#define UTILCPP_DEBUG_LOG_ON 1
#else
	#define UTILCPP_DEBUG_LOG_ON 0
#endif

#ifdef _DEBUG
	#define UTILCPP_ASSERTIONS_ON 1
	#define UTILCPP_ASSERTIONS_LOG_ON 1
	#define UTILCPP_ASSERTIONS_DEBUGBREAK_ON 1
	#define UTILCPP_ASSERTIONS_CRASH_ON 1
#else
	#define UTILCPP_ASSERTIONS_ON 0
	#define UTILCPP_ASSERTIONS_LOG_ON 0
	#define UTILCPP_ASSERTIONS_DEBUGBREAK_ON 0
	#define UTILCPP_ASSERTIONS_CRASH_ON 0
#endif


#endif